services:
  db:
    image: postgres:16
    container_name: sfos-db
    environment:
      POSTGRES_DB: sfos_core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: sfos-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config

  core:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sfos-core
    environment:
      DATABASE_URL: postgresql://core:core@db:5432/sfos_core?schema=public
      MQTT_URL: mqtt://mqtt:1883
      JWT_ACCESS_SECRET: dev_access_secret
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_SECRET: dev_refresh_secret
      JWT_REFRESH_EXPIRES: 7d
    depends_on:
      - db
      - mqtt
    ports:
      - "3000:3000"

volumes:
  db_data:
