name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy (compose on server)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            # ir para a pasta do stack
            cd ~/sfos

            # login no GHCR (ignorar erro se já estiver autenticado)
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin || true

            # atualizar imagens e subir serviços
            docker compose pull
            docker compose up -d

            # ver estado e health
            docker ps
            curl -s http://localhost:3000/health || true
